// sidebarsProjects.ts
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  projects: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;