// sidebarsTutorials.ts
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorials: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;